// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Data;

namespace WeatherApp.Data.Migrations
{
    [DbContext(typeof(CityDbContext))]
    [Migration("20190924171412_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherApp.Core.City", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("coordId");

                    b.Property<string>("country");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("coordId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WeatherApp.Core.Coord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("lat");

                    b.Property<float>("lon");

                    b.HasKey("Id");

                    b.ToTable("Coord");
                });

            modelBuilder.Entity("WeatherApp.Core.City", b =>
                {
                    b.HasOne("WeatherApp.Core.Coord", "coord")
                        .WithMany()
                        .HasForeignKey("coordId");
                });
#pragma warning restore 612, 618
        }
    }
}
